-- No longer used: profile table has been removed.
-- Auth is email/password only (Supabase Auth). Create users in Supabase Dashboard → Authentication → Users.
-- All logged-in users act as super admin.
